version: '2'
services:
    redis:
      image: redis:alpine
      container_name: ${PROJECT_NAME}-redis

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
        container_name: ${PROJECT_NAME}-elasticsearch
        restart: always
        environment:
        - discovery.type=single-node
        volumes: 
        - ./search_data:/usr/share/elasticsearch/data
        ports: 
        - 9200:9200
        - 9300:9300 

    database:
      image: postgres:9.5-alpine
      container_name: ${PROJECT_NAME}-postgres
      env_file: ./serverConfiguration/env/.env.postgres
      volumes:
         - "./postgres:/var/lib/postgresql/data"
      ports:
         - 5432:5432
      restart: always

    web:
        build:
            context: ./
            dockerfile: serverConfiguration/deploy/dev.web.docker
        container_name: ${PROJECT_NAME}-nginx
        volumes:
            - ./src/${PROJECT_NAME}/:/var/www
        ports:
            - 80:80
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: serverConfiguration/deploy/dev.app.docker
        container_name: ${PROJECT_NAME}-app
        volumes:
            - ./src/:/application
            - ./src/${PROJECT_NAME}/:/var/www
        links:
            - database
            - elasticsearch
            - redis
        tty: true
        stdin_open: true           
